spring.application.name=La_Buena_Suerte_Stock

spring.datasource.url=jdbc:mysql://localhost:3306/LA_BUENA_SUERTE_STOCK
spring.datasource.username=root
spring.datasource.password=122113Ga
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true